//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHHOCTUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHHOCTUAN()
        {
            this.TKBs = new HashSet<TKB>();
        }
    
        public int IDLICHHOC { get; set; }
        public int SOBUOIHOC { get; set; }
        public int IDBUOIHOC1 { get; set; }
        public int IDCAHOC1 { get; set; }
        public Nullable<int> IDBUOIHOC2 { get; set; }
        public Nullable<int> IDCAHOC2 { get; set; }
        public Nullable<int> IDBUOIHOC3 { get; set; }
        public Nullable<int> IDCAHOC3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKB> TKBs { get; set; }
    }
}
