//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKB
    {
        public int IDTKB { get; set; }
        public int IDSTUDENT { get; set; }
        public Nullable<System.DateTime> THOIGIANBATDAU { get; set; }
        public Nullable<System.DateTime> THOIGIANKETTHUC { get; set; }
        public int IDMONHOC { get; set; }
        public int IDCOSO { get; set; }
        public int IDTIETHOC { get; set; }
        public Nullable<int> IDLICHHOC { get; set; }
    
        public virtual COSO COSO { get; set; }
        public virtual LICHHOCTUAN LICHHOCTUAN { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual TIETHOC TIETHOC { get; set; }
    }
}
